### PR TITLE
Route::group and non-standard root namespaces support

### PR DESCRIPTION
**Pull request by adelf**
Controllers hinting now will work not only for "App" root namespaces

### CODE REVIEW

**Comment by adelf** [comment]
#35 fix this

**Comment by adelf** [comment]
Implements #8

**Comment by Haehnchen** [comment]
thanks for your work; i know its hard to get into the intellij stuff ;). but some improvments:

 - getControllerGroupPrefix should annotation as Nullable and should return null instead of an empty string
- you should reduce the try scope or remove it completely
- you can replace while statements with `PsiTreeUtil.*parent*`, so this would remove the try block also, i think ;)

@adelf would it help you if i enable testing framework here? based on the symfony plugin stuff?

**Comment by adelf** [comment]
Thank you for comments. I'll change my code.

What testing framework are you talking about?

BTW, what about try?  I thought it's ok to return default value if exception occured in function which work isn't important. To prevent exceptions like here #40. Sorry, I'm not an experienced java-developer. only C# and PHP. Maybe I don't know something.

**Comment by adelf** [comment]
I added also priority for controllers in Route::group(controllers in this group namespace have more priority).

**Comment by adelf** [comment]
@Haehnchen you don't have time for this? :)
I'm going to add some other features... Does this make sense?

**Comment by Haehnchen** [comment]
looking good so far, will merge it. but i am not happy to do so without a testcase. so i will implement test infrastructure, just wait until tomorrow ;)

**Comment by adelf** [comment]
Awesome. Thank you.

**Comment by Haehnchen** [comment]
@adelf added travis support; can you please split this merge request or combine your commits. so we have currently 3 features here:
- Non-standard root namespaces support
- Route::group support
- Prioritized controller completion

you are also welcome to provide pull requests for every feature. so we have a clean workflow. also tests by travis then. just ask for help if you need some support ;)

**Comment by Haehnchen** [comment]
@adelf i merged all commits separately and added tests, you are welcome to review. but i want to build a release asp

**Comment by adelf** [comment]
@Haehnchen thank you. I was going to make separate pull requests but didn't have time for it this 2 days. Looking forward for release

**Comment by adelf** [comment]
I tried 0.9 and seems Route::group support doesn't work :( 

        String ns = prefix;
        boolean prioritised = false;
        if(prefix == null) {
            ns = getDefaultNamespace(project);
            prioritised = true;
        }

String ns = prefix; 
=> 
String ns = getDefaultNamespace(project) + "\\" + prefix;

And... no. Anyway it's wrong. If that all other controller, which don't have this group prefix, won't be cut by Default namespace and all prioritization will be lost. So it will be:
in Route::group with namespace => 'Api':
App\Http\Controller\HomeController
AuthController
OtherController 

Sorry, but I think better is return my code here :)

**Comment by Haehnchen** [comment]
ok i see ;)

**Pull request closed without merging**
